name: 'dbt_layer_guardian'
version: '1.0.0'
config-version: 2
profile: 'dbt_layer_guardian'

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "dbt_packages"
    - "dbt_modules"

vars:
  dbt_layer_guardian:
    layer_definitions:
      - path: "staging"
        layer_name: "staging"
      - path: "intermediate"
        layer_name: "intermediate"
      - path: "marts"
        layer_name: "marts"

    # モデルの監視対象となるレイヤー名を定義します。
    # このリストに含まれるレイヤー間での依存関係を監視します。
    target_layer_names: 
      - "staging"         
      - "intermediate"         
      - "marts"

    # レイヤー間の依存関係ルールを定義します。
    # 上位のレイヤー（キー）を下位のレイヤー（値）が参照することを許可します。
    layering_rules:
      staging:
        - "intermediate"
        - "marts"
      intermediate:
        - "marts"
      marts:
        - "marts"
